version: "3.9"
services:
  start:
    env_file: .env
    image: umuttepe_hava_botu
    build:
      context: .
      dockerfile: Dockerfile
    command: umuttepe_hava_botu run
  test:
    env_file: .env
    image: umuttepe_hava_botu
    command: pytest
    depends_on: [start]
